"""Константы."""

MAX_LEN_TAG_NAME = 32
MAX_LEN_TAG_SLUG = 32

MAX_LEN_INGREDIENT_NAME = 128
MAX_LEN_INGREDIENT_MEASUREMENT_UNIT = 64

MAX_LEN_RECIPE_NAME = 200

MIN_COOKING_TIME_VALUE = 1

MAX_LEN_SHORT_LINK = 8

CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
