# Generated by Django 3.2 on 2024-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='data.Ingredients', verbose_name='Ингредиенты'),
        ),
    ]
