# Generated by Django 3.2 on 2024-09-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='data/images', verbose_name='Изображение блюда'),
            preserve_default=False,
        ),
    ]
