# Generated by Django 3.2 on 2024-09-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время приготовления в минутах'),
        ),
    ]
