# Generated by Django 3.2 on 2024-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20240905_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='data/images', verbose_name='Изображение блюда'),
        ),
    ]
