"""backend/recipes/constants.py

"""
NAME_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
MEASUREMENT_UNIT_MAX_LENGTH = 256
MIN_VALUE_VALIDATOR = 1
MAX_VALUE_VALIDATOR = 10
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
BIO_MAX_LENGTH = 254
ROLE_LENGTH_LIMIT = 13
ROLE_MAX_LENGTH = 13
PASSWORD_MIN_LENGTH = 9
