"""backend/recipes/constants.py

"""

# Постоянные моделей Ingredient, Recipe, Tag
NAME_MAX_LENGTH = 256
SLUG_MAX_LENGTH = 50
MEASUREMENT_UNIT_MAX_LENGTH = 256
MIN_VALUE_VALIDATOR = 1
MAX_VALUE_VALIDATOR = 10

# Постоянные модели User
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
PASSWORD_MIN_LENGTH = 9
