# Generated by Django 3.2.16 on 2024-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('008000', 'Зеленый'), ('ffa500', 'Оранжевый'), ('0000ff', 'Синий')], default='008000', help_text='Выберите цвет', max_length=7, unique=True, verbose_name='Цвет в HEX'),
        ),
    ]
