# Generated by Django 3.2.16 on 2024-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20240916_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название ингредиента', max_length=128, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега', max_length=32, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=None, help_text='Укажите уникальный слаг', max_length=32, verbose_name='Уникальный слаг'),
        ),
    ]
