# Generated by Django 3.2.16 on 2024-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
