# Generated by Django 5.1.2 on 2024-10-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                upload_to="static/img/users/", verbose_name="Аватар"
            ),
        ),
    ]
