# Generated by Django 3.2.3 on 2024-09-26 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='userfavoriterecipes',
            options={'default_related_name': 'favorite_recipes', 'verbose_name': 'Избранное пользователя', 'verbose_name_plural': 'Избранное пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usershoppingcartrecipes',
            options={'default_related_name': 'shopping_cart', 'verbose_name': 'Корзина пользователя с рецептом', 'verbose_name_plural': 'Корзины пользователей с рецептами'},
        ),
        migrations.RemoveConstraint(
            model_name='userfavoriterecipes',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='usershoppingcartrecipes',
            name='unique_user_shopping_cart_with_recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='recipes/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Теги рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное количество ингредиентов: 1')], verbose_name='Количество ингредиента в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/avatars/', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Имя Отчество, не более 150 символов', max_length=150, verbose_name='Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Фамилия, не более 150 символов', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userfavoriterecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='userfavoriterecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usershoppingcartrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='usershoppingcartrecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement_unit'),
        ),
        migrations.AddConstraint(
            model_name='userfavoriterecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_favorite_recipes'),
        ),
        migrations.AddConstraint(
            model_name='usershoppingcartrecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_shopping_cart_recipes'),
        ),
    ]
