# Generated by Django 3.2.3 on 2024-09-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240927_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavoriteRecipes',
            new_name='UserFavoriteRecipe',
        ),
        migrations.RenameModel(
            old_name='UserShoppingCartRecipes',
            new_name='UserShoppingCartRecipe',
        ),
        migrations.AlterModelOptions(
            name='userfavoriterecipe',
            options={'default_related_name': 'favorite_recipes', 'verbose_name': 'Избранный рецепт пользователя', 'verbose_name_plural': 'Избранные рецепты пользователей'},
        ),
    ]
