# Generated by Django 3.2.3 on 2024-09-23 16:57

import django.contrib.auth.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240923_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Адрес электронной почты уже ипользуется!'}, help_text='Адрес электронной почты, не более 254 символов', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Имя пользователя уже ипользуется!'}, help_text=('Имя пользователя, не более 150 символов.', 'Допустимые символы: буквы, цифры и @/./+/-/_'), max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='Имя пользователя содержит недопустимые символы. В имени пользователя допускается использовать буквы, цифры и символы _.@+-'), recipes.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
