# Generated by Django 3.2.3 on 2024-10-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-id',), 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
