# Generated by Django 3.2.16 on 2024-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default=None, null=True, upload_to='users/'),
        ),
    ]
