# Generated by Django 3.2.16 on 2024-09-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240909_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_image',
            new_name='avatar',
        ),
    ]
