# Generated by Django 3.2.16 on 2024-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_avatar_image_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
